import type { Metadata } from "next";
import { Play } from "next/font/google";
import "../globals.css";
import "../../scss/main.scss";
import Topbar from "@/components/base/Topbar";
import Sidebar from "@/components/base/Sidebar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const play = Play({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UAE IPTV Admin",
  description: "Generated by create next app",
};

// async function getAdmin() {
//   const cookieStore = cookies();
//   const admToken = (await cookieStore).get("admToken")?.value;

//   if (!admToken) return null;

//   try {
//     const res = await fetch("http://localhost:8000/data/admin/me", {
//       method: "POST",
//       headers: {
//         "Content-Type": "application/json",
//         cookie: `admToken=${admToken}`,
//       },
//       cache: "no-store",
//       body: JSON.stringify({}),
//     });
//     const data = await res.json();
//     return data.adminData || null;
//   } catch (err) {
//     return null;
//   }
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const admToken = (await cookieStore).get("admToken");

  if (!admToken) {
    redirect("/login");
  }

  // const admin = await getAdmin();

  return (
    <html lang="en">
      <body className={`${play.className} antialiased`}>
        <Sidebar />
        <div className="admin-content">
          <Topbar />
          <div className="px-2 lg:px-4 lg:mx-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
