import { Metadata } from "next";
import { Play } from "next/font/google";
import React from "react";
import "../../globals.css";
import "../../../scss/main.scss";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const play = Play({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UAE IPTV Admin",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = cookies();
  const admToken = (await cookieStore).get("admToken");

  if (admToken) {
    redirect("/");
  }
  return (
    <html lang="en">
      <body
        className={`${play.className} antialiased min-h-screen flex items-center justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
